export const navLinks = [
  { label: "Who we are", href: "/about" },
  {
    label: "What we do",
    href: "#",
    children: [
      { label: "Executive Travel Security", href: "/services/executive-travel" },
      { label: "Escorts", href: "/services/escorts" },
      { label: "Staff Vetting", href: "/services/staff-vetting" },
      { label: "Construction", href: "/services/construction" },
      { label: "Operations / Logistics", href: "/services/operations" },
      { label: "Agribusiness & Hospitality", href: "/services/agribusiness" },
    ],
  },
  {
    label: "Who we serve",
    href: "#",
    children: [
      { label: "Private citizens", href: "/who-we-serve/private-citizens" },
      { label: "Commercial properties", href: "/who-we-serve/commercial-properties" },
      { label: "Construction site", href: "/who-we-serve/construction-site" },
      { label: "Data center", href: "/who-we-serve/data-center" },
      { label: "Financial industry", href: "/who-we-serve/financial-industry" },
      { label: "Government and diplomatic missions", href: "/who-we-serve/government-and-diplomatic-missions" },
      { label: "Healthcare", href: "/who-we-serve/healthcare" },
      { label: "Higher education", href: "/who-we-serve/higher-education" },
      { label: "Industrial security", href: "/who-we-serve/industrial-security" },
      { label: "International organizations", href: "/who-we-serve/international-organizations" },
      { label: "Logistics and transportation", href: "/who-we-serve/logistics-and-transportation" },
      { label: "Malls, shopping centers and retail", href: "/who-we-serve/malls-shopping-centers-and-retail" },
      { label: "Manufacturing", href: "/who-we-serve/manufacturing" },
      { label: "Oil, gas and energy sectors", href: "/who-we-serve/oil-gas-and-energy-sectors" },
      { label: "Ports and logistics security", href: "/who-we-serve/ports-and-logistics-security" },
      { label: "Residential", href: "/who-we-serve/residential" },
    ],
  },
  {
    label: "Join Us",
    href: "#",
    children: [{ label: "Working at Red Salamander Security", href: "/features" }],
  },
  {
    label: "Find us",
    href: "#",
    children: [
      { label: "FCT, Abuja", href: "/contact/fct-abuja" },
      { label: "Nasarawa State", href: "/contact" },
    ],
  },
];
